### ISSUE TITLE
Error : usage: esingest.py [-h] [--region REGION] --destination DESTINATION [--verbose] esingest.py: error: argument --destination/-d is required

### ISSUE THREAD

**Issue by SyCode7** [awslabs/aws-config-to-elasticsearch#2]
Thanks fo rthis great woek.
I tried it today unfortunately, I had the error :
`root@test-virtual-machine:~/git/aws-config-to-elasticsearch/aws_config_to_es# ./esingest.py –d localhost:9200 –r us-east-1`
`usage: esingest.py [-h] [--region REGION] --destination DESTINATION
                   [--verbose]
esingest.py: error: argument --destination/-d is required`

**Comment by vbudilov** [comment]
Try --destination and --region and let me know what you get

**Comment by SyCode7** [comment]
Hi @vbudilov . Wow !! thanks it runs now. Unfortunately, I still have errors. See the output below:
`r verbose     :  response: {"error":"Content-Type header [] is not supported","status":406}...message: {"error":"Content-Type header [] is not supported","status":406}
 app         :  Couldn't add 51 to ElasticSearch. Maybe you have permission issues?
`
I am running the script as root.

**Comment by vbudilov** [comment]
Per the log message: "Maybe you have permission issues?" Running it as root isn't enough. You need to have the proper aws credentials configured: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
